import "../globals.css";
import { Poppins, Martian_Mono, Roboto_Mono } from "next/font/google";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});

const martianMono = Martian_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-martian",
});

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${martianMono.variable} ${robotoMono.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
